In [1]:
import numpy as np
import pandas as pd
import getkorean
import re

## 2.2 Building your vocabulary with a tokenizer

In [31]:
# sentence = '제 이름은 {%$CHAT.name%}입니다'  # 문장을 선언

In [2]:
sentences = '남수는 25살에 챗봇을 만들기 시작했다.\n'
sentences += '챗봇은 주로 머신러닝과 데이터로 이루어 졌다.\n'
sentences += '그는 2018년에 구로디지털단지로 이사를 갔다.\n'
sentences += '챗봇을 사람답게 바꾸는 것은 남수의 집착이었습니다.\n'

In [3]:
sentences.split('\n')

['남수는 25살에 챗봇을 만들기 시작했다.',
 '챗봇은 주로 머신러닝과 데이터가 만들었다.',
 '그는 2018년에 구로디지털단지로 이사를 갔다.',
 '챗봇을 사람답게 바꾸는 것은 남수의 집착이었습니다.',
 '']

In [30]:
# sentences.split()  # str.split()은 공백을 기준으로 분리하여 list 생성

['제', '이름은', '((0))입니다']

In [3]:
# mcslq = re.compile(r'{%[\s]*?(?P<mcsl>.+?)[\s]*?%}')

In [4]:
# var_or_entity_list = {}
# for idx, val in enumerate(mcslq.finditer(sentence)):
#     sentence = re.sub(re.escape(val.group()), '((' + str(idx) + '))', sentence)
#     var_or_entity_list[idx] = val.group()

In [23]:
def pos_tag(sentence):
    pos_result = getkorean.getkorean(sentence, True)['result']
    return [i for part in pos_result for i in part ]

In [7]:
# real_result = []
# index = re.compile(r'\(\((?P<idx>.+?)\)\)')
# for i in pos_result:
#     for j in i:
#         test = index.search(j.split('/')[0])
#         if test:
#             real_result.append(var_or_entity_list[int(test.group('idx'))]+'/mcsl')
#         else:
#             real_result.append(j)

In [24]:
corpus = {}

In [25]:
for i, sent in enumerate(sentences.splitlines()):
    result = pos_tag(sent)
    corpus[f'문장{i}'] = {token: 1 for token in result}

In [26]:
corpus

{'문장0': {'남수/NNG': 1,
  '는/JX': 1,
  '25/SN': 1,
  '살/NNB': 1,
  '에/JKB': 1,
  '챗봇을/NA': 1,
  '만들/VV': 1,
  '기/ETN': 1,
  '시작/NNG': 1,
  '하/XSV': 1,
  '았/EP': 1,
  '다/EF': 1,
  './SF': 1},
 '문장1': {'챗봇은/NA': 1,
  '주로/MAG': 1,
  '머신/NNG': 1,
  '러닝/NNG': 1,
  '과/JC': 1,
  '데이터/NNG': 1,
  '가/JKS': 1,
  '만들/VV': 1,
  '었/EP': 1,
  '다/EF': 1,
  './SF': 1},
 '문장2': {'그/NP': 1,
  '는/JX': 1,
  '2018/SN': 1,
  '년/NNB': 1,
  '에/JKB': 1,
  '구/XPN': 1,
  '로/NNG': 1,
  '디지털/NNG': 1,
  '단지/NNG': 1,
  '로/JKB': 1,
  '이사/NNG': 1,
  '를/JKO': 1,
  '가/VV': 1,
  '았/EP': 1,
  '다/EF': 1,
  './SF': 1},
 '문장3': {'챗봇을/NA': 1,
  '사람/NNG': 1,
  '답/XSA': 1,
  '게/EC': 1,
  '바꾸/VV': 1,
  '는/ETM': 1,
  '것/NNB': 1,
  '은/JX': 1,
  '남수/NNG': 1,
  '의/JKG': 1,
  '집착/NNG': 1,
  '이/VCP': 1,
  '었/EP': 1,
  '습니다/EF': 1,
  './SF': 1}}

In [29]:
df = pd.DataFrame.from_records(corpus).fillna(0).astype(int)

In [30]:
df

문장0  문장1  문장2  문장3
./SF       1    1    1    1
2018/SN    0    0    1    0
25/SN      1    0    0    0
가/JKS      0    1    0    0
가/VV       0    0    1    0
것/NNB      0    0    0    1
게/EC       0    0    0    1
과/JC       0    1    0    0
구/XPN      0    0    1    0
그/NP       0    0    1    0
기/ETN      1    0    0    0
남수/NNG     1    0    0    1
년/NNB      0    0    1    0
는/ETM      0    0    0    1
는/JX       1    0    1    0
다/EF       1    1    1    0
단지/NNG     0    0    1    0
답/XSA      0    0    0    1
데이터/NNG    0    1    0    0
디지털/NNG    0    0    1    0
러닝/NNG     0    1    0    0
로/JKB      0    0    1    0
로/NNG      0    0    1    0
를/JKO      0    0    1    0
만들/VV      1    1    0    0
머신/NNG     0    1    0    0
바꾸/VV      0    0    0    1
사람/NNG     0    0    0    1
살/NNB      1    0    0    0
습니다/EF     0    0    0    1
시작/NNG     1    0    0    0
았/EP       1    0    1    0
었/EP       0    1    0    1
에/JKB      1    0    1    0
은/JX       0    0    0    1
의/JKG      0    0    0    1
이/VCP      0    0    0    1
이사/NNG     0    0    1    0
주로/MAG     0    1    0    0
집착/NNG     0    0    0    1
챗봇은/NA     0    1    0    0
챗봇을/NA     1    0    0    1
하/XSV      1    0    0    0

In [31]:
df.T

./SF  2018/SN  25/SN  가/JKS  가/VV  것/NNB  게/EC  과/JC  구/XPN  그/NP  ...    \
문장0     1        0      1      0     0      0     0     0      0     0  ...     
문장1     1        0      0      1     0      0     0     1      0     0  ...     
문장2     1        1      0      0     1      0     0     0      1     1  ...     
문장3     1        0      0      0     0      1     1     0      0     0  ...     

     에/JKB  은/JX  의/JKG  이/VCP  이사/NNG  주로/MAG  집착/NNG  챗봇은/NA  챗봇을/NA  하/XSV  
문장0      1     0      0      0       0       0       0       0       1      1  
문장1      0     0      0      0       0       1       0       1       0      0  
문장2      1     0      0      0       1       0       0       0       0      0  
문장3      0     1      1      1       0       0       1       0       1      0  

[4 rows x 43 columns]

In [33]:
df.문장0.dot(df.문장1)

3

In [44]:
df[['문장0', '문장1']]

문장0  문장1
./SF       1    1
2018/SN    0    0
25/SN      1    0
가/JKS      0    1
가/VV       0    0
것/NNB      0    0
게/EC       0    0
과/JC       0    1
구/XPN      0    0
그/NP       0    0
기/ETN      1    0
남수/NNG     1    0
년/NNB      0    0
는/ETM      0    0
는/JX       1    0
다/EF       1    1
단지/NNG     0    0
답/XSA      0    0
데이터/NNG    0    1
디지털/NNG    0    0
러닝/NNG     0    1
로/JKB      0    0
로/NNG      0    0
를/JKO      0    0
만들/VV      1    1
머신/NNG     0    1
바꾸/VV      0    0
사람/NNG     0    0
살/NNB      1    0
습니다/EF     0    0
시작/NNG     1    0
았/EP       1    0
었/EP       0    1
에/JKB      1    0
은/JX       0    0
의/JKG      0    0
이/VCP      0    0
이사/NNG     0    0
주로/MAG     0    1
집착/NNG     0    0
챗봇은/NA     0    1
챗봇을/NA     1    0
하/XSV      1    0

In [51]:
# [(k, v) for (k, v) in (df.문장0 & df.문장1).items() if v]

overlap = []
for k, v in (df.문장0 & df.문장1).items():
    if v:
        overlap.append((k,v))
overlap

[('./SF', 1), ('다/EF', 1), ('만들/VV', 1)]

In [47]:
df.문장0 & df.문장1

./SF       1
2018/SN    0
25/SN      0
가/JKS      0
가/VV       0
것/NNB      0
게/EC       0
과/JC       0
구/XPN      0
그/NP       0
기/ETN      0
남수/NNG     0
년/NNB      0
는/ETM      0
는/JX       0
다/EF       1
단지/NNG     0
답/XSA      0
데이터/NNG    0
디지털/NNG    0
러닝/NNG     0
로/JKB      0
로/NNG      0
를/JKO      0
만들/VV      1
머신/NNG     0
바꾸/VV      0
사람/NNG     0
살/NNB      0
습니다/EF     0
시작/NNG     0
았/EP       0
었/EP       0
에/JKB      0
은/JX       0
의/JKG      0
이/VCP      0
이사/NNG     0
주로/MAG     0
집착/NNG     0
챗봇은/NA     0
챗봇을/NA     0
하/XSV      0
dtype: int32

In [49]:
for k, v in (df.문장0 & df.문장1).items():
    print('k:',k, 'v:',v)

k: ./SF v: 1
k: 2018/SN v: 0
k: 25/SN v: 0
k: 가/JKS v: 0
k: 가/VV v: 0
k: 것/NNB v: 0
k: 게/EC v: 0
k: 과/JC v: 0
k: 구/XPN v: 0
k: 그/NP v: 0
k: 기/ETN v: 0
k: 남수/NNG v: 0
k: 년/NNB v: 0
k: 는/ETM v: 0
k: 는/JX v: 0
k: 다/EF v: 1
k: 단지/NNG v: 0
k: 답/XSA v: 0
k: 데이터/NNG v: 0
k: 디지털/NNG v: 0
k: 러닝/NNG v: 0
k: 로/JKB v: 0
k: 로/NNG v: 0
k: 를/JKO v: 0
k: 만들/VV v: 1
k: 머신/NNG v: 0
k: 바꾸/VV v: 0
k: 사람/NNG v: 0
k: 살/NNB v: 0
k: 습니다/EF v: 0
k: 시작/NNG v: 0
k: 았/EP v: 0
k: 었/EP v: 0
k: 에/JKB v: 0
k: 은/JX v: 0
k: 의/JKG v: 0
k: 이/VCP v: 0
k: 이사/NNG v: 0
k: 주로/MAG v: 0
k: 집착/NNG v: 0
k: 챗봇은/NA v: 0
k: 챗봇을/NA v: 0
k: 하/XSV v: 0


In [53]:
response = []
for k, v in (df.문장0 & df.문장1).items():
    if v:
        response.append((k,v))
response

[('./SF', 1), ('다/EF', 1), ('만들/VV', 1)]

In [8]:
token_sequence = real_result
vocab = sorted(set(token_sequence))

In [9]:
', '.join(vocab)

'{%$CHAT.name%}/mcsl, ㅂ니다/EC, 은/JX, 의/JKG, 이/VCP, 이름/NNG, 저/NP'

In [10]:
num_tokens = len(token_sequence)
vocab_size = len(vocab)

In [11]:
num_tokens

7

In [12]:
vocab_size

7

In [13]:
onehot_vectors = np.zeros((num_tokens, vocab_size), int)

In [14]:
for i, word in enumerate(token_sequence):
    onehot_vectors[i, vocab.index(word)] = 1

In [15]:
print(' '.join(vocab))

{%$CHAT.name%}/mcsl ㅂ니다/EC 은/JX 의/JKG 이/VCP 이름/NNG 저/NP


In [16]:
onehot_vectors

array([[0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0, 0]])

In [17]:
df = pd.DataFrame(onehot_vectors, columns=vocab)

In [18]:
df

{%$CHAT.name%}/mcsl  ㅂ니다/EC  은/JX  의/JKG  이/VCP  이름/NNG  저/NP
0                    0       0     0      0      0       0     1
1                    0       0     0      1      0       0     0
2                    0       0     0      0      0       1     0
3                    0       0     1      0      0       0     0
4                    1       0     0      0      0       0     0
5                    0       0     0      0      1       0     0
6                    0       1     0      0      0       0     0

In [19]:
df[df == 0] = ''
df

{%$CHAT.name%}/mcsl ㅂ니다/EC 은/JX 의/JKG 이/VCP 이름/NNG 저/NP
0                                                       1
1                                     1                  
2                                                  1     
3                               1                        
4                   1                                    
5                                           1            
6                          1

In [20]:
sentence_bow = {}
for token in real_result:
    sentence_bow[token] = 1

In [21]:
sorted(sentence_bow.items())

[('{%$CHAT.name%}/mcsl', 1),
 ('ㅂ니다/EC', 1),
 ('은/JX', 1),
 ('의/JKG', 1),
 ('이/VCP', 1),
 ('이름/NNG', 1),
 ('저/NP', 1)]

In [23]:
df = pd.DataFrame(pd.Series({token: 1 for token in real_result}), columns=['sent'])

In [24]:
df

sent
저/NP                    1
의/JKG                   1
이름/NNG                  1
은/JX                    1
{%$CHAT.name%}/mcsl     1
이/VCP                   1
ㅂ니다/EC                  1

In [25]:
df.T

저/NP  의/JKG  이름/NNG  은/JX  {%$CHAT.name%}/mcsl  이/VCP  ㅂ니다/EC
sent     1      1       1     1                    1      1       1

In [79]:
v1 = pd.np.array([1, 2, 3])
v2 = pd.np.array([2, 3, 4])
v1.dot(v2)

20

In [80]:
(v1 * v2).sum()

20

In [81]:
sum([x1 * x2 for x1, x2 in zip(v1, v2)])

20

In [82]:
print(v1)
print(v1.shape)

[1 2 3]
(3,)


In [75]:
print(v1.reshape(-1, 1))
print(v1.shape)

[[1]
 [2]
 [3]]
(3,)


In [76]:
print(v1.T)
print(v1.shape)

[1 2 3]
(3,)


In [86]:
a = np.array([1,2,3,4,5,6])
aa = np.array([[1,2,3,4,5,6]])

In [102]:
v1 @ v2

20

In [88]:
a.T

array([1, 2, 3, 4, 5, 6])

In [93]:
a.shape

(6,)

In [90]:
aa

array([[1, 2, 3, 4, 5, 6]])

In [92]:
aa.shape

(1, 6)